# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 610)
        MainWindow.setStyleSheet("background-color: rgb(255, 228, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 30, 471, 51))
        self.label.setStyleSheet("font: 26pt \"宋体\";\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 430, 351, 161))
        self.label_2.setStyleSheet("border:1px solid black;\n"
"border-radius: 12px;\n"
"background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 410, 81, 41))
        self.label_3.setStyleSheet("font: 12pt \"宋体\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 231, 451))
        self.label_4.setStyleSheet("border:1px solid black;\n"
"border-radius: 12px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 81, 41))
        self.label_5.setStyleSheet("font: 12pt \"宋体\";")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 380, 81, 41))
        self.label_7.setStyleSheet("font: 12pt \"宋体\";")
        self.label_7.setObjectName("label_7")
        self.label_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_pic.setGeometry(QtCore.QRect(260, 140, 351, 271))
        self.label_pic.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-radius: 12px;")
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 120, 111, 41))
        self.label_9.setStyleSheet("font: 12pt \"宋体\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(620, 140, 331, 451))
        self.label_10.setStyleSheet("border:1px solid black;\n"
"border-radius: 12px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(630, 160, 311, 421))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(430, 450, 171, 61))
        self.label_res.setStyleSheet("font: 75 22pt \"宋体\";\n"
"color: rgb(170, 0, 0);\n"
"background-color: transparent;")
        self.label_res.setObjectName("label_res")
        self.label_pro = QtWidgets.QLabel(self.centralwidget)
        self.label_pro.setGeometry(QtCore.QRect(430, 510, 121, 61))
        self.label_pro.setStyleSheet("font: 75 22pt \"宋体\";\n"
"color: rgb(170, 0, 0);\n"
"background-color: transparent;")
        self.label_pro.setObjectName("label_pro")
        self.pushButton_pic_begin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pic_begin.setGeometry(QtCore.QRect(70, 280, 141, 41))
        self.pushButton_pic_begin.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"font: 12pt \"宋体\";\n"
"border-radius: 12px;")
        self.pushButton_pic_begin.setObjectName("pushButton_pic_begin")
        self.pushButton_folder_begin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_folder_begin.setGeometry(QtCore.QRect(60, 490, 141, 41))
        self.pushButton_folder_begin.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"font: 12pt \"宋体\";\n"
"border-radius: 12px;")
        self.pushButton_folder_begin.setObjectName("pushButton_folder_begin")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 110, 880, 1))
        self.line_2.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"background-color: rgb(84, 84, 84);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_pic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pic.setGeometry(QtCore.QRect(70, 220, 161, 31))
        self.lineEdit_pic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_pic.setObjectName("lineEdit_pic")
        self.pushButton_pic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pic.setGeometry(QtCore.QRect(40, 220, 41, 31))
        self.pushButton_pic.setStyleSheet("image: url(ui/图像.png);\n"
"background-color: rgb(217, 217, 217);")
        self.pushButton_pic.setText("")
        self.pushButton_pic.setObjectName("pushButton_pic")
        self.res_type_2 = QtWidgets.QLabel(self.centralwidget)
        self.res_type_2.setGeometry(QtCore.QRect(290, 450, 131, 61))
        self.res_type_2.setStyleSheet("font: 75 20pt \"宋体\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: transparent;")
        self.res_type_2.setObjectName("res_type_2")
        self.res_type_3 = QtWidgets.QLabel(self.centralwidget)
        self.res_type_3.setGeometry(QtCore.QRect(290, 510, 111, 61))
        self.res_type_3.setStyleSheet("font: 75 20pt \"宋体\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: transparent;")
        self.res_type_3.setObjectName("res_type_3")
        self.lineEdit_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_folder.setGeometry(QtCore.QRect(70, 430, 161, 31))
        self.lineEdit_folder.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_folder.setObjectName("lineEdit_folder")
        self.pushButton_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_folder.setGeometry(QtCore.QRect(40, 430, 41, 31))
        self.pushButton_folder.setStyleSheet("image: url(ui/文件夹.png);\n"
"background-color: rgb(217, 217, 217);")
        self.pushButton_folder.setText("")
        self.pushButton_folder.setObjectName("pushButton_folder")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 350, 211, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_pic.raise_()
        self.label_9.raise_()
        self.tableWidget.raise_()
        self.label_res.raise_()
        self.label_pro.raise_()
        self.pushButton_pic_begin.raise_()
        self.pushButton_folder_begin.raise_()
        self.line_2.raise_()
        self.lineEdit_pic.raise_()
        self.pushButton_pic.raise_()
        self.res_type_2.raise_()
        self.res_type_3.raise_()
        self.lineEdit_folder.raise_()
        self.pushButton_folder.raise_()
        self.line_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于深度学习的植物识别系统"))
        self.label.setText(_translate("MainWindow", "基于深度学习的植物识别系统"))
        self.label_3.setText(_translate("MainWindow", " 识别结果"))
        self.label_5.setText(_translate("MainWindow", " 单张识别"))
        self.label_7.setText(_translate("MainWindow", " 多张识别"))
        self.label_9.setText(_translate("MainWindow", " 识别结果信息"))
        self.label_res.setText(_translate("MainWindow", "结果1"))
        self.label_pro.setText(_translate("MainWindow", "100%"))
        self.pushButton_pic_begin.setText(_translate("MainWindow", "开始识别"))
        self.pushButton_folder_begin.setText(_translate("MainWindow", "开始识别"))
        self.res_type_2.setText(_translate("MainWindow", "植物名称："))
        self.res_type_3.setText(_translate("MainWindow", "置信度："))

